#!/bin/sh

. /etc/init.d/functions

RETVAL=0

prog=dhcp6c
dhcp6c=/sbin/dhcp6c
lockfile=/var/lock/subsys/dhcp6c

lease_file=/var/lib/dhcpv6/client-leases*
duid_file=/var/lib/dhcpv6/dhcp6c_duid

# Check that networking is up.
# networking is not up, return 1 for generic error
. /etc/sysconfig/network
[ $NETWORKING = "no" ] && exit 1

start() {
    # return 5 if program is not installed
    [ -x $dhcp6c ] || exit 5

    # return 6 if program is not configured
    [ -f /etc/dhcp6c.conf ] || exit 6
    [ -f /etc/sysconfig/dhcp6c ] || exit 6
    . /etc/sysconfig/dhcp6c

    if [ -z "$DHCP6CIF" ]; then
        logger -s -t "$prog" -p "daemon.info" "Warning: $prog listening on ALL interfaces"
    fi

    echo -n $"Starting $prog: "

    # XXX
    rm -f $lease_file
    rm -f $duid_file

    daemon $dhcp6c -c /etc/dhcp6c.conf $DHCP6CARGS $DHCP6CIF
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && touch $lockfile
    return $RETVAL
}

stop() {
    echo -n $"Shutting down $prog: "
    killproc $prog -TERM
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && success || failure
    echo
    rm -f $lockfile
    return $RETVAL
}

# See how we were called.
case "$1" in
    start)
        start
        RETVAL=$?
        ;;
    stop)
        stop
        RETVAL=$?
        ;;
    restart|force-reload)
        stop && start
        RETVAL=$?
        ;;
    try-restart|reload)
        RETVAL=3
        ;;
    condrestart)
        if [ -f $lockfile ]; then
            stop && start
        fi
        ;;
    status)
        status $prog
        RETVAL=$?
        ;;
    *)
        echo $"Usage: $0 {start|stop|restart|try-restart|reload|force-reload|status}"
        RETVAL=3
        ;;
esac

exit $RETVAL
